### ISSUE TITLE
PhantomJS was not killed in 2000 ms, sending SIGKILL

### ISSUE THREAD

**Issue by sylvain-hamel** [karma-runner/karma-phantomjs-launcher#27]
Hi,

On our machines `karma-phantomjs-launcher` is not able stop PhantomJS when using `singleRun: true`.

The output is:

`PhantomJS was not killed in 2000 ms, sending SIGKILL`

I have to `CTRL+C` to stop it.

Tested on:
- Windows 8, x64
- Windows 7, x86

Thanks

**Comment by Ciantic** [comment]
I'm encountering this with 1.0.4, I wonder what is the go to solution these days.

**Comment by gh0st** [comment]
I've noticed this only fails when passing the `--code-coverage` flag.

**Comment by priyankabmohite** [comment]
> I've noticed this only fails when passing the `--code-coverage` flag.

We are facing same issue even we are not passing `--code-coverage` flag

**Comment by ghost** [comment]
@priyankabmohite and anyone else still following this. Our solution to this and other phantomjs related issues (including it using a very dated webkit engine) was pretty blunt in the end; we moved to ChromeHeadless and have had zero problems since.

Update: I've just noticed the PhantomJS project is now archived, so jumping ship seems especially prudent.
